### PR TITLE
ci: disable cross-version tests in Dependabot PRs

### PR DESCRIPTION
**Pull request by jjohannes**
These require the 'Build software' step to write to the Gradle remote cache. But Dependabot PRs to not have write access to the cache.

I think this is a reasonable compromise as, if an updates breaks something, it is most likely in Java code.

### CODE REVIEW

**Review by nathanklick — CHANGES_REQUESTED** [review]
Why not just add the Gradle Cache credentials to the dependabot secrets?

**Comment by jjohannes** [comment]
> Why not just add the Gradle Cache credentials to the dependabot secrets?

If that is possible, that's even besser. Can you do that @andrewb1269hg and then we can discard this PR?

**Comment by andrewb1269** [comment]
> > Why not just add the Gradle Cache credentials to the dependabot secrets?
> 
> If that is possible, that's even besser. Can you do that @andrewb1269hg and then we can discard this PR?

Yes, I believe that's possible. I'll write an issue to capture this effort and we can close this PR out by tying it to the new issue.

**Comment by andrewb1269** [comment]
@jjohannes I have added `GRADLE_CACHE_USERNAME` and `GRADLE_CACHE_PASSWORD` to the dependabot secrets. These should be available for usage.

**Comment by jjohannes** [comment]
Thanks @andrewb1269hg. Credentials work as this PR shows https://github.com/hashgraph/hedera-cryptography/pull/175

Closing this one.

**Pull request closed without merging**
